version: "3"
services:
  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
      - /Users/msi/Desktop/temp_outputs:/var/lib/orthanc/import
      - ./scripts:/scripts
    restart: always
    networks:
      - pacs

  ohif_viewer:
    container_name: ohif
    image: ohif/viewer
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs

  python_restapi:
    container_name: python
    image: python:3.7
    build: .
    volumes:
      - ./scripts:/scripts
      - /Users/msi/Desktop/temp_outputs:/var/lib/orthanc/import
    command: >
      bash -c "apt-get update && apt-get install -y curl && 
      pip install watchdog requests && 
      python3 /scripts/watch_import.py"
    networks:
      - pacs
    depends_on: [ pacs, ]

networks:
  pacs:
    external: true
    driver: bridge
